### ISSUE TITLE
"No module named dateutil.relativedelta" when setting up DB on local install

### ISSUE THREAD

**Issue by tjlahr** [hackerunion-archives/hackerunion.org#46]
After a fresh install, after I've activated the virtual environment and run `pip install -r var/etc/requirements.txt`, when I run `DJANGO_LOCAL=True ./manage.py syncdb --noinput` to setup the DB, I get the follwing error: 

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 8, in <module>
    from django.core.management.sql import custom_sql_for_model, emit_post_sync_signal
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/core/management/sql.py", line 6, in <module>
    from django.db import models
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/db/__init__.py", line 11, in <module>
    if DEFAULT_DB_ALIAS not in settings.DATABASES:
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/utils/functional.py", line 184, in inner
    self._setup()
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/tjlahr/Dev/HU/hackerunion-arel/env/lib/python2.7/site-packages/django/conf/__init__.py", line 95, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'petri.settings' (Is it on sys.path?): No module named dateutil.relativedelta
```

The solution, as @brandondiamond figured out, is to remove `librabbitmq==0.9.9` from `var/etc/requirements.txt`.

Not sure if other people are running into this, but it's a bizzarre stumbling block for new users.

**Comment by mathisonian** [comment]
This may be related: http://stackoverflow.com/questions/8418636/python-cannot-find-dateutil-relativedelta

**Comment by tjlahr** [comment]
Well, 1-4 didn't help on that list but I've since rebooted my computer (step 5) and everything seems to work fine. Closing until somebody else hits this.
